# Generated by Django 6.0.4 on 2026-04-27 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(default='test_bank', max_length=255),
        ),
    ]
