# Generated by Django 6.0.4 on 2026-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_alter_ledgerentry_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idempotencykey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
